### ISSUE TITLE
Not working for some image.

### ISSUE THREAD

**Issue by yoon-boom** [clydeev/corrupt-jpeg-detector#1]
![00002789571a1ca1](https://user-images.githubusercontent.com/7377941/27713283-de29bb12-5cdf-11e7-994f-6ed532760591.jpg)
![0000411119129247](https://user-images.githubusercontent.com/7377941/27713284-de30ac2e-5cdf-11e7-9ac6-e5adfd9dbc67.jpg)

are the images not working.
But if you are to run through ImageMagick, it throws error on both image premature end of data segment.

**Comment by clydeev** [comment]
Thanks for opening this issue sir. I will look into these images why it cannot be detected. Will you updates soon.

**Comment by clydeev** [comment]
Hi Yoon Lee. Codes have been updated now. Try it again and let me know if there's a problem.

**Comment by yoon-boom** [comment]
@clydeev awesome!
